movie_wl/routes.py
from flask import Blueprint, render_template, redirect, session, request, url_for, flash, abort, current_app, jsonify, send_file
from flask_login import login_required, current_user, LoginManager, login_user, logout_user
from datetime import datetime
from werkzeug.utils import secure_filename
from movie_wl.config import Config
from movie_wl.imdb_utils import get_top_10_movies, get_bottom_10_movies
from flask_wtf.csrf import generate_csrf
from time import localtime, strftime
from movie_wl import db, bcrypt, mail, socketio, ROOMS
from movie_wl.models import Post, User, PostMain, Messages, Like, UploadMusic
from movie_wl.forms import MovieForm, RegistrationForm, LoginForm, EditDetails, PostForm, EditProfileForm, EditPost, ResetPasswordForm, RequestResetForm, ChangeEmailForm,ChangePasswordForm, UploadMusicForm
import secrets
from PIL import Image
import os
import pathlib
from sqlalchemy import func, or_
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token
from movie_wl.drive_utils import upload_to_drive, get_drive_service
from google.oauth2 import service_account
import requests
import io
from movie_wl.google_login_utils import initiate_google_login, handle_google_callback
from werkzeug.security import check_password_hash
from flask_mail import Message
from flask_socketio import send, emit, SocketIO, join_room, leave_room
from sqlalchemy.exc import SQLAlchemyError

                                    
pages = Blueprint("pages", __name__, template_folder="templates", static_folder="static")

@pages.route('/')
def main():
    if current_user.is_authenticated:
        page = request.args.get("page", 1, type=int)
        sort_option = request.args.get("sort_option", "Newest")  # Default sorting option is "Date"
        form = PostForm()
        
        followed_user_ids = [user.id for user in current_user.followed]
        followed_user_ids.append(current_user.id)
        
        # Query top-rated movies from the current user and the users they follow
        top_movies = Post.query.filter(Post.user_id.in_(followed_user_ids)).order_by(Post.rate.desc()).limit(10).all()
        
        # Determine the sorting method based on the selected option
        if sort_option == "Oldest":
            posts = PostMain.query.filter(PostMain.user_id.in_(followed_user_ids)).order_by(PostMain.date_posted.asc()).paginate(page=page, per_page=5)
        elif sort_option == "Most Liked":
            # Join the Like table and count the number of likes for each post
            posts = PostMain.query \
                .outerjoin(Like, PostMain.id == Like.post_id) \
                .filter(PostMain.user_id.in_(followed_user_ids)) \
                .group_by(PostMain.id) \
                .order_by(func.count(Like.id).desc()) \
                .paginate(page=page, per_page=5)
        else:
            posts = PostMain.query.filter(PostMain.user_id.in_(followed_user_ids)).order_by(PostMain.date_posted.desc()).paginate(page=page, per_page=5)

        post_likes = {}  # Dictionary to store likes for each post
        for post in posts.items:
            post_likes[post.id] = Like.query.filter_by(post_id=post.id).count()

        # Fetch top and bottom 10 movies using IMDbPY
        imdb_top_10 = get_top_10_movies()
        imdb_bottom_10 = get_bottom_10_movies()
        members = User.query.filter(User.id != current_user.id).order_by(User.username.desc()).limit(10).all()
        csrf_token = generate_csrf()  # Generate CSRF token
        return render_template("main.html", title="MS Network", form=form, posts=posts, members=members, top_movies=top_movies, csrf_token=csrf_token, post_likes=post_likes, sort_option=sort_option,
            imdb_top_10=imdb_top_10,
            imdb_bottom_10=imdb_bottom_10)
    
    # If user is not authenticated, redirect to login
    return redirect(url_for(".login"))

@pages.route('/', methods=['POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        # Store content and username in the database
        post = PostMain(user_id=current_user.id, content=form.content.data)
        db.session.add(post)
        db.session.commit()
        
    return redirect(url_for(".main"))
    
    


    



@pages.route("/watchlist", methods=["GET", "POST"])
@login_required
def watchlist():
    sort_option = request.args.get("sort_option", "Date")  # Default sorting option is "Date"
    page = request.args.get("page", 1, type=int)

    # Fetch all movies posted by the user
    user_movies = Post.query.filter_by(user_id=current_user.id)

    # Fetch all movie IDs from the watchlist
    watchlist_movie_ids = [movie.id for movie in current_user.watchlist]

    # Query all movies from the watchlist based on their IDs
    watchlist_movies = Post.query.filter(Post.id.in_(watchlist_movie_ids))
    

    # Combine both lists
    all_movies = user_movies.union(watchlist_movies)
    

    # Apply sorting based on the selected option directly in the database query
    if sort_option == "Year":
        all_movies = all_movies.order_by(Post.year.desc())
    elif sort_option == "Rate":
        all_movies = all_movies.order_by(Post.rate.desc())
    elif sort_option == "Alphabetical":
        all_movies = all_movies.order_by(Post.title)
    else:
        all_movies = all_movies.order_by(Post.date_posted.desc())

    # Paginate the sorted list
    movie_data = all_movies.paginate(page=page, per_page=5)
    print(movie)

    return render_template("watchlist.html", title="Movies Watchlist", movie_data=movie_data, sort_option=sort_option)


@pages.route("/search")
def search():
    if current_user.is_authenticated:
        q = request.args.get("q")
        if q: 
                results = Post.query.filter(
                (Post.user_id == current_user.id) &  \
                (Post.title.icontains(q) | Post.director.icontains(q)) \
            ).order_by(Post.date_posted.desc()).limit(5).all()
        else:
            results = []

        return render_template("search.html", results=results)

        
@pages.route("/edit_post/<int:post_id>/edit_post", methods=["GET","POST"])
@login_required
def edit_post(post_id):
    form = EditPost()
    post = PostMain.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.content = form.content.data

        db.session.commit()

        return redirect(url_for(".main"))
    
    elif request.method == 'GET':
        form.content.data = post.content
    
    return render_template("edit_post.html", title="Edit Post", form=form)

@pages.route("/account/edit_post/<int:post_id>/edit_post", methods=["GET","POST"])
@login_required
def edit_post_acc(post_id):
    form = EditPost()
    post = PostMain.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.content = form.content.data

        db.session.commit()

        return redirect(url_for(".account"))
    
    elif request.method == 'GET':
        form.content.data = post.content
    
    return render_template("edit_post.html", title="Edit Post", form=form)
               


@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    form = MovieForm()

    if form.validate_on_submit():
        post = Post(title=form.title.data, director=form.director.data, year=form.year.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for(".watchlist"))
    return render_template("new_movie.html", title="Add Movie", form=form)


@pages.get("/movie/<int:post_id>")
@login_required
def movie(post_id):
    try:
        movie_data = Post.query.get_or_404(post_id)
        return render_template("movie_details.html", title="Movie Details", movie_data=movie_data)
    except Exception as e:
        
        abort(500)

@pages.get("/movie/<int:post_id>/rate")
@login_required
def rate_movie(post_id):
    rate = int(request.args.get("rate"))
    # Update the rate for the specified movie in the database
    post = Post.query.filter_by(id=post_id).first()
    if post:
        post.rate = rate
        db.session.commit()
    
    return redirect(url_for(".movie", post_id=post_id))

@pages.route("/movie/<int:post_id>/watch", methods=["GET", "POST"])
@login_required
def watch_today(post_id):
    try:
        post = Post.query.get_or_404(post_id)
        post.last_watched = datetime.now()
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        flash("An error occurred while updating the watch time.", "error")
        return redirect(url_for("pages.error"))
    
    return redirect(url_for(".movie", post_id=post_id))

@pages.route("/edit_movie/<int:post_id>/edit_movie", methods=["GET","POST"])
@login_required
def edit_movie(post_id):
    post = Post.query.get_or_404(post_id)
    form = EditDetails()

    if form.validate_on_submit():
        # Update existing post data
        post.title = form.title.data
        post.director = form.director.data
        post.year = form.year.data
        #Add additional data
        post.genre = form.genre.data
        post.video_link = form.video_link.data
        post.description = form.description.data
        post.main_cast = form.main_cast.data

        db.session.commit()
        
        return redirect(url_for(".movie", post_id=post_id))
    
    elif request.method == 'GET':
        # Prefill the form with existing post data
        form.title.data = post.title
        form.director.data = post.director
        form.year.data = post.year
        form.genre.data = post.genre
        form.video_link.data = post.video_link
        form.description.data = post.description
        form.main_cast.data = post.main_cast
    return render_template('movie_form.html', title='Edit Movie', form=form)

@pages.route("/movie/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_movie(post_id):
    # Attempt to get the movie from the Post database
    post = Post.query.get_or_404(post_id)
    

movie_wl/templates/macro/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(class_="form__field") }}

    {% for error in field.errors %}
        <span class="form__error"> {{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}


{% macro render_area_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(rows=4, class_="form__field", style="resize: none") }}

    {% for error in field.errors %}
        <span class="form__error"> {{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}


{% macro render_post_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(rows=4, class_="form__field", style="resize: none") }}

    {% for error in field.errors %}
        <span class="form__error"> {{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

{% macro render_edit_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(class_="form__file-field") }}

    {% for error in field.errors %}
        <span class="form__error"> {{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

movie_wl/templates/macro/footer.html
{% macro footer() %}
<footer class="footer">
    <small>Copyright &copy;2024. Moviesphere Network. All rights reserved.</small>
</footer>
{% endmacro %}

movie_wl/templates/macro/nav.html
{% from "macro/svgs.html" import moon, sun %}
{% macro header(theme, current_user) %}


<header class="header">
    <div class="nav-container">
        <a href="{{ url_for('pages.main') }}" class="header__logo">
            <svg xmlns="http://www.w3.org/2000/svg" class="logo__icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
</svg> <span class="logo__name">Moviesphere Network</span>
        </a>


        


        <nav class="nav">
            {% if not current_user.is_authenticated %}
                <a
                    href="{{ url_for('pages.login') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.login') }}"
                >
                    <span class="nav__item">Log In</span>
                </a>
                <a
                    href="{{ url_for('pages.register') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.register') }}"
                >
                    <span class="nav__item">Registration</span>
                </a>

            {% else %}

            <a href="{{ url_for('pages.settings') }}" class="settings_icon">
                <img src="{{ url_for('static', filename='settings.png') }}" alt="Chat Icon" title="Settings" class="settings_icon_img">
                <!-- You can add a caption if needed -->
                <!-- Caption: Click me -->
            </a>
            <a href="{{ url_for('pages.direct_message') }}" class="messages_icon">
                <img src="{{ url_for('static', filename='messages.png') }}" alt="Chat Icon" title="Messages" class="messages_icon_img">
                <!-- You can add a caption if needed -->
                <!-- Caption: Click me -->
            </a>
            
            <a href="{{ url_for('pages.chat') }}" class="chat_icon">
                <img src="{{ url_for('static', filename='chat_icon.png') }}" alt="Chat Icon" title="Chat Rooms" class="chat_icon_img">
                <!-- You can add a caption if needed -->
                <!-- Caption: Click me -->
            </a>
                <form action="{{ url_for('pages.search') }}" method="GET" class="nav__search-form">
                    
                    <i class="fas fa-search nav__search-icon"></i>
                    <input type="text" name="q" placeholder="Search Watchlist" class="nav__search-input" hx-get="/search" hx-trigger="keyup changed delay:500ms" hx-target="#results">
                    
                   
                </form>
            
                <a
                    href="{{ url_for('pages.watchlist') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.watchlist') }}"
                >
                    <span class="nav__item">Watchlist</span>
                </a>
                <a
                    href="{{ url_for('pages.store') }}"
                    class="nav__link"
                >   
                    <span class="nav__item">Music</span>

                </a>  
                    <div class="nav__profile2">
                        <a href="{{ url_for('pages.account') }}"></a>  
                            <img src="{{ url_for('static', filename='dropdown_icon.png') }}" alt="Dropdown Icon" class="nav__image2">
                        
                            <div class="nav__dropdown2">
                                <a href="{{ url_for('pages.members') }}" class="nav__dropdown2-item">Members</a>
                                <a href="{{ url_for('pages.top_rated_movies') }}" class="nav__dropdown2-item">Top Movies</a>                 
                                <a href="{{ url_for('pages.direct_message') }}" class="nav__dropdown2-item">Messages</a>
                                <a href="{{ url_for('pages.chat') }}" class="nav__dropdown2-item">Chat</a>
                                <a href="{{ url_for('pages.settings') }}" class="nav__dropdown2-item">Settings</a>
                                <a href="{{ url_for('pages.about') }}" class="nav__dropdown2-item">About</a>
                            </div>
                    </div>
                    
                
                    
                

                <div class="nav__profile">
                    <a href="{{ url_for('pages.account') }}"></a>  
                        <img src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}" alt="Profile Picture" class="nav__image">
                    
                        <div class="nav__dropdown">
                            <a href="{{ url_for('pages.account') }}" class="nav__dropdown-item">Profile</a>
                            <a href="{{ url_for('pages.edit_profile') }}" class="nav__dropdown-item">Edit Profile</a>
                            <a href="{{ url_for('pages.logout') }}" class="nav__dropdown-item">Log Out</a>
                        </div>
                </div>

                

            {% endif %}

            <a
                href="{{ url_for('pages.toggle_theme', current_page=request.path) }}"
                class="nav__link"
            >
                <span class="nav__item">
                    {% if theme == "dark" %}
                        {{ sun("nav__icon") }}
                    {% else %}
                        {{ moon("nav__icon") }}
                    {% endif %}
                </span>
            </a>
        </nav>
    </div>
</header>
    <body>
        


{% endmacro %}

movie_wl/templates/macro/svgs.html
{% macro star(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
</svg>
{% endmacro %}

{% macro pencil(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
</svg>
{% endmacro %}

{% macro moon(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
</svg>
{% endmacro %}

{% macro sun(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
</svg>
{% endmacro %}