movie_wl/routes.py
from flask import Blueprint, render_template, redirect, session, request, url_for, flash, abort, current_app, jsonify, send_file
from flask_login import login_required, current_user, LoginManager, login_user, logout_user
from datetime import datetime
from werkzeug.utils import secure_filename
from movie_wl.config import Config
from movie_wl.imdb_utils import get_top_10_movies, get_bottom_10_movies
from flask_wtf.csrf import generate_csrf
from time import localtime, strftime
from movie_wl import db, bcrypt, mail, socketio, ROOMS
from movie_wl.models import Post, User, PostMain, Messages, Like, UploadMusic
from movie_wl.forms import MovieForm, RegistrationForm, LoginForm, EditDetails, PostForm, EditProfileForm, EditPost, ResetPasswordForm, RequestResetForm, ChangeEmailForm,ChangePasswordForm, UploadMusicForm
import secrets
from PIL import Image
import os
import pathlib
from sqlalchemy import func, or_
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token
from movie_wl.drive_utils import upload_to_drive, get_drive_service
from google.oauth2 import service_account
import requests
import io
from movie_wl.google_login_utils import initiate_google_login, handle_google_callback
from werkzeug.security import check_password_hash
from flask_mail import Message
from flask_socketio import send, emit, SocketIO, join_room, leave_room
from sqlalchemy.exc import SQLAlchemyError

                                    
pages = Blueprint("pages", __name__, template_folder="templates", static_folder="static")

@pages.route('/')
def main():
    if current_user.is_authenticated:
        page = request.args.get("page", 1, type=int)
        sort_option = request.args.get("sort_option", "Newest")  # Default sorting option is "Date"
        form = PostForm()
        
        followed_user_ids = [user.id for user in current_user.followed]
        followed_user_ids.append(current_user.id)
        
        # Query top-rated movies from the current user and the users they follow
        top_movies = Post.query.filter(Post.user_id.in_(followed_user_ids)).order_by(Post.rate.desc()).limit(10).all()
        
        # Determine the sorting method based on the selected option
        if sort_option == "Oldest":
            posts = PostMain.query.filter(PostMain.user_id.in_(followed_user_ids)).order_by(PostMain.date_posted.asc()).paginate(page=page, per_page=5)
        elif sort_option == "Most Liked":
            # Join the Like table and count the number of likes for each post
            posts = PostMain.query \
                .outerjoin(Like, PostMain.id == Like.post_id) \
                .filter(PostMain.user_id.in_(followed_user_ids)) \
                .group_by(PostMain.id) \
                .order_by(func.count(Like.id).desc()) \
                .paginate(page=page, per_page=5)
        else:
            posts = PostMain.query.filter(PostMain.user_id.in_(followed_user_ids)).order_by(PostMain.date_posted.desc()).paginate(page=page, per_page=5)

        post_likes = {}  # Dictionary to store likes for each post
        for post in posts.items:
            post_likes[post.id] = Like.query.filter_by(post_id=post.id).count()

        # Fetch top and bottom 10 movies using IMDbPY
        imdb_top_10 = get_top_10_movies()
        imdb_bottom_10 = get_bottom_10_movies()
        members = User.query.filter(User.id != current_user.id).order_by(User.username.desc()).limit(10).all()
        csrf_token = generate_csrf()  # Generate CSRF token
        return render_template("main.html", title="MS Network", form=form, posts=posts, members=members, top_movies=top_movies, csrf_token=csrf_token, post_likes=post_likes, sort_option=sort_option,
            imdb_top_10=imdb_top_10,
            imdb_bottom_10=imdb_bottom_10)
    
    # If user is not authenticated, redirect to login
    return redirect(url_for(".login"))

@pages.route('/', methods=['POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        # Store content and username in the database
        post = PostMain(user_id=current_user.id, content=form.content.data)
        db.session.add(post)
        db.session.commit()
        
    return redirect(url_for(".main"))
    
    


    



@pages.route("/watchlist", methods=["GET", "POST"])
@login_required
def watchlist():
    sort_option = request.args.get("sort_option", "Date")  # Default sorting option is "Date"
    page = request.args.get("page", 1, type=int)

    # Fetch all movies posted by the user
    user_movies = Post.query.filter_by(user_id=current_user.id)

    # Fetch all movie IDs from the watchlist
    watchlist_movie_ids = [movie.id for movie in current_user.watchlist]

    # Query all movies from the watchlist based on their IDs
    watchlist_movies = Post.query.filter(Post.id.in_(watchlist_movie_ids))
    

    # Combine both lists
    all_movies = user_movies.union(watchlist_movies)
    

    # Apply sorting based on the selected option directly in the database query
    if sort_option == "Year":
        all_movies = all_movies.order_by(Post.year.desc())
    elif sort_option == "Rate":
        all_movies = all_movies.order_by(Post.rate.desc())
    elif sort_option == "Alphabetical":
        all_movies = all_movies.order_by(Post.title)
    else:
        all_movies = all_movies.order_by(Post.date_posted.desc())

    # Paginate the sorted list
    movie_data = all_movies.paginate(page=page, per_page=5)
    print(movie)

    return render_template("watchlist.html", title="Movies Watchlist", movie_data=movie_data, sort_option=sort_option)


@pages.route("/search")
def search():
    if current_user.is_authenticated:
        q = request.args.get("q")
        if q: 
                results = Post.query.filter(
                (Post.user_id == current_user.id) &  \
                (Post.title.icontains(q) | Post.director.icontains(q)) \
            ).order_by(Post.date_posted.desc()).limit(5).all()
        else:
            results = []

        return render_template("search.html", results=results)

        
@pages.route("/edit_post/<int:post_id>/edit_post", methods=["GET","POST"])
@login_required
def edit_post(post_id):
    form = EditPost()
    post = PostMain.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.content = form.content.data

        db.session.commit()

        return redirect(url_for(".main"))
    
    elif request.method == 'GET':
        form.content.data = post.content
    
    return render_template("edit_post.html", title="Edit Post", form=form)

@pages.route("/account/edit_post/<int:post_id>/edit_post", methods=["GET","POST"])
@login_required
def edit_post_acc(post_id):
    form = EditPost()
    post = PostMain.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.content = form.content.data

        db.session.commit()

        return redirect(url_for(".account"))
    
    elif request.method == 'GET':
        form.content.data = post.content
    
    return render_template("edit_post.html", title="Edit Post", form=form)
               


@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    form = MovieForm()

    if form.validate_on_submit():
        post = Post(title=form.title.data, director=form.director.data, year=form.year.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for(".watchlist"))
    return render_template("new_movie.html", title="Add Movie", form=form)


@pages.get("/movie/<int:post_id>")
@login_required
def movie(post_id):
    try:
        movie_data = Post.query.get_or_404(post_id)
        return render_template("movie_details.html", title="Movie Details", movie_data=movie_data)
    except Exception as e:
        
        abort(500)

@pages.get("/movie/<int:post_id>/rate")
@login_required
def rate_movie(post_id):
    rate = int(request.args.get("rate"))
    # Update the rate for the specified movie in the database
    post = Post.query.filter_by(id=post_id).first()
    if post:
        post.rate = rate
        db.session.commit()
    
    return redirect(url_for(".movie", post_id=post_id))

@pages.route("/movie/<int:post_id>/watch", methods=["GET", "POST"])
@login_required
def watch_today(post_id):
    try:
        post = Post.query.get_or_404(post_id)
        post.last_watched = datetime.now()
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        flash("An error occurred while updating the watch time.", "error")
        return redirect(url_for("pages.error"))
    
    return redirect(url_for(".movie", post_id=post_id))

@pages.route("/edit_movie/<int:post_id>/edit_movie", methods=["GET","POST"])
@login_required
def edit_movie(post_id):
    post = Post.query.get_or_404(post_id)
    form = EditDetails()

    if form.validate_on_submit():
        # Update existing post data
        post.title = form.title.data
        post.director = form.director.data
        post.year = form.year.data
        #Add additional data
        post.genre = form.genre.data
        post.video_link = form.video_link.data
        post.description = form.description.data
        post.main_cast = form.main_cast.data

        db.session.commit()
        
        return redirect(url_for(".movie", post_id=post_id))
    
    elif request.method == 'GET':
        # Prefill the form with existing post data
        form.title.data = post.title
        form.director.data = post.director
        form.year.data = post.year
        form.genre.data = post.genre
        form.video_link.data = post.video_link
        form.description.data = post.description
        form.main_cast.data = post.main_cast
    return render_template('movie_form.html', title='Edit Movie', form=form)

@pages.route("/movie/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_movie(post_id):
    # Attempt to get the movie from the Post database
    post = Post.query.get_or_404(post_id)
    

movie_wl/templates/change_password.html
{% from "macro/fields.html" import render_text_field %}
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='movies.css') }}" />
    
{% endblock %}

{% block main_content %}


{% with messages = get_flashed_messages(with_categories=true) %}
{% for category, message in messages %}
    <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
{% endfor %}
{% endwith %}
<form name="edit_password" method="post" novalidate class="form">
<div class="form__container">
    <div class="login-header-login">Change Password</div>    
    {{ form.hidden_tag() }}
    {{ render_text_field(form.current_password) }}
    {{ render_text_field(form.new_password) }}
    {{ render_text_field(form.confirm_new_password) }}



    <div>
        {{ form.submit(class_="button button--form") }}
    </div>
</div>

</form>

{% endblock %}

movie_wl/templates/chat.html
{% extends "layout.html" %}

{% block head_content %}

    <link rel="stylesheet" href="{{ url_for('static', filename='chat.css') }}" />
{% endblock %}

{% block main_content %}
<div class="chat-section" id="chat-section">
    <nav class="sidebar" id="sidebar">
        <h4>ROOMS</h4>
        {% for room in rooms %}

        <p class="select-room{% if room == active_room %} active-room{% endif %}">{{ room|title }}</p>

        {% endfor %}

        
       
    </nav>
    
    <div class="rightside-pannel" id="rightside-pannel">
        
        <div class="display-message-section" id="display-message-section">
            <!-- Messages will be displayed here -->
        </div>
        <div class="input-area" id="input-area">
            <textarea class="user_message" id="user_message" placeholder="Type here..." rows="1"></textarea>
            <button type="button" class="send_message" id="send_message">SEND</button>
        </div>
        
        <script>
            document.getElementById('user_message').addEventListener('input', function() {
                const textarea = this;
                const lineHeight = parseInt(window.getComputedStyle(textarea).lineHeight);
                const paddingHeight = parseInt(window.getComputedStyle(textarea).paddingTop) + parseInt(window.getComputedStyle(textarea).paddingBottom);
                const scrollHeight = textarea.scrollHeight - paddingHeight;
        
                if (scrollHeight > lineHeight) {
                    textarea.rows = Math.ceil(scrollHeight / lineHeight);
                } else {
                    textarea.rows = 1;
                }
            });
        </script>
    </div>
</div>

<script type="text/javascript">
    const username = `{{ username }}`;
</script>

<script src="{{ url_for('static', filename='scripts/chat_page.js') }}"></script>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.4/socket.io.js"></script>
<script src="{{ url_for('static', filename='scripts/socketio.js') }}"></script>
{% endblock %}

movie_wl/templates/edit_post.html
{% from "macro/fields.html" import render_text_field, render_area_field %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />
{% endblock %}

{% block main_content %}
    <form name="edit_post" method="post" novalidate class="form">
        <div class="form__container">
            <div class="login-header-login">Edit Post</div>
            {{ form.hidden_tag() }}           
            {{ render_area_field(form.content) }}



            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
            
        </div>
    </form>
{% endblock %}

movie_wl/templates/layout.html
{% from "macro/nav.html" import header %}
{% from "macro/footer.html" import footer%}

<!DOCTYPE html>
<html lang="en">
<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">
    
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title> {{ title | default('Movie Watchlist') }}</title>
        <link href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='reset.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous">

            {% block head_content %} {% endblock %}
        </head>
        
        <body>
            
            <div class="background__image"></div> <!-- Make sure to remove the <img> tag here -->
            <!-- Rest of your form content -->
            
            
            <!-- Include jQuery library -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            
            <!-- JavaScript code for adjusting background image height -->
            <script>
                function adjustBackgroundImageHeight() {
                    var windowHeight = $(window).height();
                    var imagePath = '/static/cnmtc.jpg'; // Adjust the path accordingly
                    $('.background__image').css('background-image', 'url(' + imagePath + ')');
                    $('.background__image').height(windowHeight);
                }
            
                // Call the function to adjust background image height
                adjustBackgroundImageHeight();
            
                // Trigger resize event to adjust background image height dynamically
                $(window).on('resize', adjustBackgroundImageHeight);
            </script>
            
            {{ header(session.get("theme"), current_user) }}

            <main class="main">
                
                {% block main_content %} {% endblock %}
            </main>
            {{ footer() }}
        </body>
</html>

movie_wl/templates/main.html
{% from "macro/fields.html" import render_text_field, render_area_field, render_post_field %}
{% extends "layout.html" %}
{% from "macro/svgs.html" import star, pencil %}

{% block head_content %}
<script>
    function likePost(postId) {
    fetch(`/like/${postId}`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
        },
        body: JSON.stringify({})
    })
    .then(() => {
        window.location.reload(); // Reload the page after the request is completed
    })
    .catch(error => console.error('Error:', error));
}
</script>
    <link rel="stylesheet" href="{{ url_for('static', filename='main_page.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='movie_details.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='account.css') }}" />
{% endblock %}


{% block main_content %}

    <!-- Content specific to the main page -->
    <div class="input-container">
        
        <form method="post" action="{{ url_for('pages.create_post') }}">
            {{ form.hidden_tag() }}
            <div class="styled-input">
                <textarea id="content" name="content" placeholder="Write something..." class="wide-input"></textarea>
            </div>
            <button type="submit" class="post-button">Post</button> <!-- Add the button here -->

            


        </form>
        
    </div>
    
        
    
    <div class="post-container">
        <div class="neon-line-main"></div>
        <form id="sort-form" action="{{ url_for('pages.main') }}" method="get">
            <div class="sort-dropdown-main">
                <label for="sort-option">Sort by:</label>
                <select id="sort-option" name="sort_option" onchange="handleSortOption()">
                    <option value="Newest">Newest</option>
                    <option value="Oldest" {% if sort_option == "Oldest" %} selected {% endif %}>Oldest</option>
                    <option value="Most Liked" {% if sort_option == "Most Liked" %} selected {% endif %}>Most Liked</option>
                </select>
            </div>
        </form>
    
    
        <script>
            function handleSortOption() {
                document.getElementById("sort-form").submit();
            }
        </script>
        {% for post in posts.items %}
        <div class="post">
            <div class="post-header">
        
                {% if current_user == post.user %}
                    <a href="{{ url_for('pages.account') }}" class="post-header a">
                {% else %}
                    <a href="{{ url_for('pages.user_profile', username=post.user.username) }}" class="post-header a">
                {% endif %}
                    <img src="{{ url_for('static', filename='profile_pics/' + post.user.image_file) }}" alt="Profile Picture" class="post-header-img">
                    <h3 class="post-username">{{ post.user.username }}</h3> <!-- Display the username -->
    </a>
                {% if current_user.is_authenticated and post.user_id == current_user.id %}
                
                <a class="post__edit" href="{{ url_for('pages.edit_post', post_id=post.id) }}">Edit</a>
                <form action="{{ url_for('pages.delete_post', post_id=post.id)}}" method="post" style="display: inline;">
                    <input type="submit" value="Delete" class="delete__post">
                       
                </form>
                
                {% endif %}
            </div>
            
            <p class="post-content">{{ post.content }}</p>
            <p class="post-date">{{ post.date_posted.strftime('%d %b %Y') }}</p> <!-- Display the date_posted -->
            <div class="post-actions">
                <button class="like-button" onclick="likePost('{{ post.id }}')">Like</button>
                <a href="{{ url_for('pages.post_likes', post_id=post.id) }}">
                    {% if post_likes.get(post.id, 0) > 0 %}
                        <span class="likes-count">{{ post_likes.get(post.id, 0) }}</span>
                    {% endif %}
                </a>
            </div>
        </div>
        {% endfor %}
        <div class="pagination-container">
            
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                <a class="pagination-current" href="{{ url_for('pages.main', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                <a class="pagination" href="{{ url_for('pages.main', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
            {% endif %}
            {% endfor %}
        </div>    
    </div>

        

<!-- New container for the list of members -->
<div class="right-container">
    <a href="{{ url_for('pages.members') }}">
    <h2>MEMBERS</h2>
    </a>
    <ul class="member-list">
        {% for member in members %}
        <li class="member-list-item">
            <a href="{{ url_for('pages.user_profile', username=member.username) }}" class="member-list-item a">
                <img src="{{ url_for('static', filename='profile_pics/' + member.image_file) }}" alt="Profile Photo" class="member-list-item img">
                {{ member.username }}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
<!-- Container for top movies  -->
<div class="movie-container">
    <a href="https://www.imdb.com/list/ls003992425/" target="_blank" class="top-movies-link">
        <h2>TOP IMDB MOVIES</h2>
    </a>
    <ul class="movie-list">
        {% if imdb_top_10 %}
            {% for movie in imdb_top_10 %}
                <li class="movie-list-item">
                    {{ movie.title }} ({{ movie.year }})
                </li>
            {% endfor %}
        {% else %}
            <li>No top movies available at the moment.</li>
        {% endif %}
    </ul>
</div>

<!-- Container for bottom movies -->
<div class="movie-container-2">
    <a href="https://www.imdb.com/chart/bottom" target="_blank" class="bottom-movies-link">
        <h2>LOWEST RATED IMDB</h2>
    </a>
    <ul class="movie-list">
        {% if imdb_bottom_10 %}
            {% for movie in imdb_bottom_10 %}
                <li class="movie-list-item">
                    {{ movie.title }} ({{ movie.year }})
                </li>
            {% endfor %}
        {% else %}
            <li>No bottom movies available at the moment.</li>
        {% endif %}
    </ul>
</div>


<div class="left-container">
    <a href="{{ url_for('pages.top_rated_movies') }}">
    <h2>TOP RATED MOVIES</h2>
    </a>
    <ul class="movie-list">
        <!-- Check if the top_movies list is not empty -->
        {% if top_movies %}
            <!-- Initialize a flag to check if there are any rated movies -->
            {% set has_rated_movies = False %}
            
            <!-- Loop through the movies and check if any have been rated -->
            {% for movie in top_movies %}
                {% if movie.rate and movie.rate > 0 %}
                    <!-- Set flag to True when a rated movie is found -->
                    {% set has_rated_movies = True %}
                    <li class="movie-list-item">
                        <a href="{{ url_for('pages.top_rated_movies') }}" class="movie-list-item a">
                            {{ movie.title }}
                            <div class="movie-rating">
                                {% for i in range(1, 6) %}
                                <svg class="star {% if movie.rate >= i %}star--filled{% endif %}" viewBox="0 0 24 24">
                                    <path d="M12 2l2.35 7.24h7.65l-6.19 4.49 2.35 7.26L12 17.36l-6.16 4.63 2.35-7.26-6.19-4.49h7.65z"></path>
                                </svg>
                                {% endfor %}
                            </div>
                        </a>
                    </li>
                {% endif %}
            {% endfor %}

        {% else %}
            <!-- If the top_movies list is empty, display the message -->
            <li class="movie-list-item">
                <p class="no-rating-message">You haven't added any rated movie yet.</p>
            </li>
        {% endif %}
    </ul>
    
</div>


{% endblock %}

movie_wl/templates/messages.html
{% extends "layout.html" %}
{% block content %}
  <h1>Messages</h1>

  <!-- Display the user's messages -->
  <h2>Messages</h2>
  <ul>
    {% for message in messages %}
      <li>{{ message.sender.username }}: {{ message.content }}</li>
    {% endfor %}
  </ul>

  <!-- Display the user's conversations -->
  <h2>Conversations</h2>
  <ul>
    {% for conversation in conversations %}
      <li>{{ conversation.other_user.username }}</li>
    {% endfor %}
  </ul>

  <!-- Form to send a new message -->
  <h2>Send Message</h2>
  <form action="{{ url_for('pages.send_message') }}" method="post">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.recipient.label }} {{ form.recipient(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.content.label }} {{ form.content(class="form-control") }}
    </div>
    <button type="submit" class="btn btn-primary">{{ form.submit.label }}</button>
  </form>
{% endblock %}

movie_wl/templates/new_movie.html
{% from "macro/fields.html" import render_text_field %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />
{% endblock %}

{% block main_content %}
    <form name="add_movie" method="post" novalidate class="form">
        <div class="form__container">
            <div class="login-header-login">Add Movie</div>
            {{ form.hidden_tag() }}           
            {{ render_text_field(form.title) }}
            {{ render_text_field(form.director) }}
            {{ render_text_field(form.year) }}

            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
            
        </div>
    </form>
{% endblock %}

movie_wl/templates/register.html
{% from "macro/fields.html" import render_text_field %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />
{% endblock %}

{% block main_content %}
    <form name="register" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}
        <div class="form__container">
            <div class="login-header-login">REGISTER</div>
            {{ form.hidden_tag() }}
            {{ render_text_field(form.username) }}
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
            {{ render_text_field(form.confirm_password) }}

            <span class="form__small">
                Already have an account? <a href="{{ url_for('pages.login') }}" class="form__link">Log In Here</a>
            </span>

            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
 

    </form>

{% endblock %}

movie_wl/templates/reset_password_request.html
{% from "macro/fields.html" import render_text_field %}

{% extends "layout.html" %}


{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />
{% endblock %}

{% block main_content %}
    <form name="reset_password_request" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}
        <div class="form__container">
            
            {{ form.hidden_tag() }}
            {{ render_text_field(form.email) }}
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
            
        </div>
    </form>
{% endblock %}

movie_wl/templates/search.html
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='movies.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='forms.css') }}" />
{% endblock %}


{% block main_content %}
{% if results %}
    <table class="table">
        <colgroup>             
            <col style="width: 60%">
            <col style="width: 25%">
            <col style="width: 15%">
            <col style="width: 10%">
        </colgroup>
        <thead>
            <tr class="table__header">
                <th class="table__cell table__cell--header">Title</th>
                <th class="table__cell table__cell--header">Release Date</th>
                <th class="table__cell table__cell--header"><div class="login-header-login-search">WATCHLIST</div></th>
                <th class="table__cell table__cell--header"></th>
            </tr>
        </thead>
        <tbody id="results">
            {% for result in results %}
            <tr>
                <td class="table__cell">
                    <p class="table__movieTitle">{{ result.title }}</p>
                    <p class="table__movieDirector">By {{ result.director }}</p>
                </td>
                <td class="table__cell">{{ result.year }}</td>
                <td class="table__cell">
                    <a href="{{ url_for('pages.edit_movie', post_id=result.id)}}" class="table__link__edit">Edit</a>
                </td>
                <td class="table__cell">
                    <form action="{{ url_for('pages.delete_movie', post_id=result.id)}}" method="post" style="display: inline;">
                        <input type="submit" value="Delete" class="delete__movie">
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="table__empty">No Results Found.</p>
{% endif %}
{% endblock %}

movie_wl/templates/settings.html
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='settings.css') }}" />
 
{% endblock %}

{% block main_content %}
    <div class="settings-content-section">
        <h1>SETTINGS</h1>
        <h2>Account Settings</h2>

        <div class="settings-media">
            <ul>
                <li><a href="{{ url_for('pages.change_email') }}">Change Email</a>
                    </li>


                <li><a href="{{ url_for('pages.change_password') }}">Change Password</a>
                
                    </li>
                <!-- Add more options here if needed -->
            </ul>
            {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
            {% if category == 'success' %}
                <span class="sform__flash sform__flash--{{ category }}">{{ message }}</span>
            {% endif %}
        {% endfor %}
    {% endwith %}
        </div>
    

    <div class="settings-1">
        <h2>Edit Profile</h2>
        <a href="{{ url_for('pages.edit_profile') }}">Edit Profile</a>
        
    </div>

    
</div>
{% endblock %}